---
title: Annual Weekly Salary by NAICS
author: Dean Hansen
self-contained: true
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}

## Load packages
library(tidyverse)
library(scales)
library(ggrepel)
library(plotly)
library(gt)
library(gtExtras)

## Load data
earnings_by_industry <- readr::read_csv("/Users/deanhansen/Recent Scripts/Statistics Canada/data-raw/earnings_by_industry_data.csv")

```

Now we look at some data.

```{r}

earnings_by_industry$YEAR |> 
  ggplot(aes(ANNUAL_WEEKLY_SALARY_IN_DOLLARS)) +
  geom_histogram() +
  facet_wrap(~YEAR)

```

```{r}

p <-
  earnings_by_industry |> 
  filter(GEO == "Canada", EMPLOYEE_TYPE != "All employees", OVERTIME == "Excluding overtime") |> 
  group_by(YEAR) |> 
  slice_max(order_by = ANNUAL_WEEKLY_SALARY, n = 10) |> 
  ggplot(aes(x = YEAR, y = ANNUAL_WEEKLY_SALARY, colour = NAICS)) +
  geom_point() +
  geom_line() +
  theme(legend.position = "bottom")

earnings_by_industry |> 
  filter(GEO == "Canada", EMPLOYEE_TYPE != "All employees", OVERTIME == "Excluding overtime") |> 
  group_by(YEAR) |> 
  slice_max(order_by = ANNUAL_WEEKLY_SALARY, n = 10) |> 
  ggplot(aes(x = YEAR, y = ANNUAL_WEEKLY_SALARY, colour = NAICS)) +
  geom_point() +
  geom_line() +
  theme(legend.position = "bottom")

ggplotly(p)

```


```{r}

df <- matrix(data = rnorm(30*2) , nrow = 30, ncol = 2)

```
